name = "NRSTmak"
author = "ClemenPine"
link = "github.com/ClemenPine/nrstmak"
year = 2022

[formats.standard]
matrix = [
  ["q", "w", "y", "p", "b", "j", "k", "o", "u", ","],
  ["n", "r", "s", "t", "d", "l", "h", "a", "e", "i"],
  ["z", "x", "c", "f", "g", "v", "m", "'", ";", "."],
]

map = {}
home_row = 1
